export const apps = [
  {
    name: 'tibia[api]',
    script: 'dist/main.js',
    instances: 2,
    exec_mode: 'cluster',
    watch: false,
    autorestart: true,
    max_memory_restart: '512M',
    node_args: ['--max-old-space-size=512'],
    kill_timeout: 5000,
    wait_ready: true,
    listen_timeout: 10000,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    error_file: 'logs/api-error.log',
    out_file: 'logs/api-out.log',
    env: {
      NODE_ENV: 'production',
    },
  },
  {
    name: 'tibia[schema]',
    script: 'npx prisma studio',
    watch: false,
    autorestart: true,
    interpreter_args: '--harmony',
    max_memory_restart: '256M',
    node_args: ['--max-old-space-size=256'],
  },
];
