// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import path from 'path';
import { defineConfig } from 'prisma/config';

const envFile =
  process.env.DOTENV_CONFIG_PATH ||
  (process.env.NODE_ENV === 'development'
    ? '.env.development.local'
    : '.env');

dotenv.config({ path: path.resolve(process.cwd(), envFile), override: true });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
